### ISSUE TITLE
Cannot find module 'fstream' in cacheDependencyManager

### ISSUE THREAD

**Issue by Patman12** [swarajban/npm-cache#42]
After updating from version 0.5.1 to 0.5.3 today, npm-cache immediately throws the following error:

`Error: Cannot find module 'fstream'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/patrickdavis/cvent.git/developer-portal/developer-portal-ui/node_modules/npm-cache/cacheDependencyManagers/cacheDependencyManager.js:10:15)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)`

Not sure how fstream is supposed to be installed into npm-cache, but it's completely missing. Installing fstream and adding it to npm-cache's node_modules folder resolves this issue.

**Comment by swarajban** [comment]
Hm, I'm not seeing this. What version of node/npm are you on?

**Comment by swarajban** [comment]
Ah, looks like it's broken on 0.12/0.10

**Comment by Patman12** [comment]
Yup, I'm still on node 0.12.7, the PR referencing this issue should resolve this

**Comment by swarajban** [comment]
Just pushed, published, and released fix. Check out npm-cache version 0.5.4

**Comment by Patman12** [comment]
Thank you!
